config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs do 
    resources :comments    
  end
	root "blogs#index"  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :user
	has_many :comments
  validates :title, :content, presence: true  
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :blog  
	belongs_to :user
	belongs_to  :parent, class_name: 'Comment', optional: true
  has_many    :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy	
end

app/models/user.rb
class User < ApplicationRecord  
  has_many :blogs
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def full_name
    "#{first_name} #{last_name}"          
  end

  def is_blog_author? blog
    self.id == blog.user_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception	
	before_action :configure_permitted_parameters, :only => [:create], if: :devise_controller?

  def configure_permitted_parameters  	
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation, :title_id, :province_id, :first_name, :last_name])    
  end   

	def after_sign_in_path_for(resource)
	  blogs_path
	end

	def after_sign_out_path_for resource
		blogs_path			
	end		
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_blog, only: %i[ show edit update destroy ]
  
  def index
    @blogs = Blog.all
  end
  
  def show
  end

  def new    
    @blog = Blog.new    
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def new
   @blog = Blog.find(params[:blog_id])
   @comment = @blog.comments.new(parent_id: params[:parent_id])		
	end

  def create
  	# debugger
    @blog = Blog.find(params[:blog_id])
    json_params = comment_params.merge({user_id: current_user.id})
    @comment = @blog.comments.create(json_params)
    redirect_to blog_path(@blog)
  end	

  private
    def comment_params
      params.require(:comment).permit(:body, :parent_id)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= blog.user&.full_name %></td>
        <td><%= link_to 'Show', blog %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<% if current_user.is_blog_author? @blog %>
  <%= link_to 'Edit', edit_blog_path(@blog) %> |
  <%= link_to 'Destroy', @blog, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>  
<%= link_to 'Back', blogs_path %>

<h2>Comments</h2>
<% @blog.comments.each do |comment| %>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
    <div>
      <% if current_user.is_blog_author? @blog %>
        <%= link_to 'Reply', new_blog_comment_path(@blog, parent_id: comment.id), remote: true, class: 'd-block' %>
      <% end %>
    </div>
   <% if comment.replies.any? %>
      <% comment.replies.each do |reply| %> 
        <div>
          <%= render partial: 'comments/reply', locals: { reply: reply } %>
        </div>
      <% end %>
    <% end %>
    <div id="reply-form-<%= comment.id %>"></div>
  </p>
<% end %>


<%= render partial: 'comments/comment_form' %>

app/views/comments/_comment_form.html.erb
<h2>Add a comment:</h2>
<%= form_with model: [ @blog, @blog.comments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/_reply.html.erb
<strong>Reply:</strong>
<%= reply.body %>

app/views/comments/_reply_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_with(model: [@blog, @comment]) do |f| %>
      <%= f.hidden_field :parent_id %>
      <div class="form-group">
        <%= f.label 'Reply' %>
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', blog_path(@blog), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/comments/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>").innerHTML = ("<%= j render 'reply_form', comment: @comment %>")

app/views/layouts/_header.html.erb
<div style="float:right; margin-top: -40px; margin-right: 20px;"><h3><%= current_user.full_name if current_user %></h1></div>

<div style="float:right;">
  <% if current_user %>
    <%= link_to "Log out", destroy_user_session_path , method: :delete%>
  <%else%>
    <%= link_to "Login", new_user_session_path %>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render :partial => 'layouts/header' %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>      
      <%= yield %>
    </div>     
  </body>
</html>